# version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres_nimbuscore
    restart: always
    environment:
      POSTGRES_DB: nimbuscoredb
      POSTGRES_USER: nimbuscore
      POSTGRES_PASSWORD: n1mbus.C0r3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nimbuscorenet

  web:
    build: ./backend
    container_name: django_nimbuscore
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - nimbuscorenet

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - nimbuscorenet

volumes:
  postgres_data:

networks:
  nimbuscorenet:
