# version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres_nimbuscore
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nimbuscorenet

  web:
    build: ./backend
    container_name: django_nimbuscore
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${BPORT}"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "${BPORT}:${BPORT}"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - nimbuscorenet

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "${SONARQUBE_PORT}:${SONARQUBE_PORT}"
    networks:
      - nimbuscorenet

  nginx:
    image: nginx:latest
    container_name: nginx_nimbuscore
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - static_volume:/static
      - ./config/conf.d:/etc/nginx/conf.d #aquí va el archivo local.conf
      - ./config/certs:/certs  # directorio del key y cert
    depends_on:
      - web
    networks:
      - nimbuscorenet

volumes:
  postgres_data:
  static_volume:

networks:
  nimbuscorenet:
