# version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flask_backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - nimbuscorenet

  db:
    image: postgres:13
    container_name: postgres_nimbuscore
    restart: always
    environment:
      POSTGRES_USER: nimbuscore
      POSTGRES_PASSWORD: n1mbus.C0r3
      POSTGRES_DB: nimbuscoredb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nimbuscorenet

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/nimbuscoredb
      SONARQUBE_JDBC_USERNAME: nimbuscore
      SONARQUBE_JDBC_PASSWORD: n1mbus.C0r3
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db
    networks:
      - nimbuscorenet

networks:
  nimbuscorenet:
    driver: bridge

volumes:
  postgres_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
