# Generated by Django 4.2.21 on 2025-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorIntentos',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('contador', models.PositiveIntegerField()),
                ('ultimo_intento', models.DateTimeField()),
            ],
        ),
    ]
