# Generated by Django 4.2.23 on 2025-06-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otptemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('puerto', models.PositiveIntegerField(default=22)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
